# Generated by Django 4.0.6 on 2024-02-26 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psicoapp', '0002_user_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='psicoapp.tipousuario'),
        ),
    ]
