# Generated by Django 4.0.6 on 2024-02-26 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psicoapp', '0004_localformulario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localformulario',
            options={'verbose_name': 'Local de formulário de um usuário', 'verbose_name_plural': 'Locais de formulário de um usuário'},
        ),
    ]
