# Generated by Django 4.0.6 on 2024-02-26 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psicoapp', '0005_alter_localformulario_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='localAplicacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='psicoapp.localformulario'),
        ),
    ]
