# Generated by Django 4.0.6 on 2024-02-26 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psicoapp', '0006_formulario_localaplicacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocalAplicacao',
        ),
    ]
