# Generated by Django 4.0.6 on 2024-03-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicoapp', '0007_delete_localaplicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrauInstrucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definicaoGrau', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Grau de instrução',
                'verbose_name_plural': 'Graus de instrução',
            },
        ),
    ]
