# Generated by Django 4.0.6 on 2024-03-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psicoapp', '0008_grauinstrucao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='grau_de_instrucao',
        ),
    ]
