# Generated by Django 5.0.3 on 2024-04-30 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psicoapp", "0010_formulario_grauinstrucao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="psicoapp.areausuario",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="tipo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="psicoapp.tipousuario",
            ),
        ),
    ]
