# Generated by Django 5.0.3 on 2025-01-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psicoapp", "0011_alter_user_area_alter_user_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulario",
            name="encaminhado_por",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="formulario",
            name="especialidade",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="formulario",
            name="prontuario",
            field=models.CharField(default="", max_length=255),
        ),
    ]
