# Generated by Django 5.0.3 on 2025-01-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "psicoapp",
            "0012_formulario_encaminhado_por_formulario_especialidade_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulario",
            name="campo_questoes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="data_e_hora",
            field=models.DateTimeField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="escolha_sexo",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="idade",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
