# Generated by Django 5.0.3 on 2025-01-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psicoapp", "0013_alter_formulario_campo_questoes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulario",
            name="especialidade",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
